//
//  Feats.h
//  TheTruePCMan
//
//  Created by Lowy on 11/10/2019.
//  Copyright © 2019 Lowy. All rights reserved.
//

#ifndef Feats_h
#define Feats_h

char *FeatNames[] = {
    "Acrobatic",
    "Acrobatic Steps",
    "Agile Maneuvers (Combat)",
    "Alertness",
    "Alignment Channel",
    "Animal Affinity",
    "Arcane Armor Mastery (Combat)",
    "Aracan Armor Training (Combat)",
    "Arcane Strike (Combat)",
    "Armor Proficiency, Heavy (Combat)",
    "Armor Proficiency, Light (Combat)",
    "Armor Proficiency, Medium (Combat)",
    "Athletic",
    "Augment Summoning",
    
    "Bleeding Critical (Combat, Critical)",
    "Blind-Fight (Combat)",
    "Blinding Critical (Combat, Critical)",
    "Brew Potion (Item Creation)",
    
    "Catch Off-Guard (Combat)",
    "Channel Smite (Combat)",
    "Cleave (Combat)",
    "Combat Casting",
    "Combat Expertise (Combat)",
    "Combat Reflexes (Combat)",
    "Command Undead",
    "Craft Magic Arms and Armor (Item Creation)",
    "Craft Rod (Item Creation)",
    "Craft Staff (Item Creation)",
    "Craft Wand (Item Creation)",
    "Craft Wondrous Item (Item Creation)",
    "Critical Focus (Combat)",
    "Critical Mastery (Combat)",
    
    "Dazzling Display (Combat)",
    "Deadly Aim (Combat)",
    "Deadly Stroke (Combat)",
    "Deafening Critical (Combat, Critical)",
    "Deceitful",
    "Defensive Combat Training (Combat)",
    "Deflect Arrows (Combat)",
    "Deft Hands",
    "Diehard",
    "Disruptive (Combat)",
    "Dodge (Combat)",
    "Double Slice (Combat)",
    
    "Elemental Channel",
    "Empower Spell (Metamagic)",
    "Endurance",
    "Enlarge Spell (Metamagic)",
    "Eschew Materials",
    "Exhausting Critical (Combat, Critical)",
    "Exotic Weapon Proficiency (Combat)",
    "Extend Spell (Metamagic)",
    "Extra Channel",
    "Extra Ki",
    "Extra Lay On Hands",
    "Extra Mercy",
    "Extra Performance",
    "Extra Rage",
    
    "Far Shot (Combat)",
    "Fleet",
    "Forge Ring (Item Creation)",
    
    "Gorgon's Fist (Combat)",
    "Great Cleave (Combat)",
    "Great Fortitude",
    "Greater Bull Rush (Combat)",
    "Greater Disarm (Combat)",
    "Greater Feint (Combat)",
    "Greater Grapple (Combat)",
    "Greater Overrun (Combat)",
    "Greater Penetrating Strike (Combat)",
    "Greater Shield Focus (Combat)",
    "Greater Spell Focus",
    "Greater Spell Penetration",
    "Greater Sunder (Combat)",
    "Greater Trip (Combat)",
    "Greater Two-Weapon Fighting (Combat)",
    "Greater Vital Strike (Combat)",
    "Greater Weapon Focus (Combat)",
    "Greater Weapon Specialization (Combat)",
    
    "Heighten Spell (Metamagic)",
    
    "Improved Bull Rush (Combat)",
    "Improved Channel",
    "Improved Counterspell",
    "Improved Critical (Combat)",
    "Improved Disarm (Combat)",
    "Improved Familiar",
    "Improved Feint (Combat)",
    "Improved Grapple (Combat)",
    "Improved Great Fortitude",
    "Improved Initiative (Combat)",
    "Improved Iron Will",
    "Improved Lightning Reflexes",
    "Improved Overrun (Combat)",
    "Improved Precise Shot (Combat)",
    "Improved Shield Bash (Combat)",
    "Improved Sunder (Combat)",
    "Improved Trip (Combat)",
    "Improved Two-Weapon Fighting (Combat)",
    "Improved Unarmed Strike (Combat)",
    "Improved Vital Strike (Combat)",
    "Improved Weapon Mastery (Combat)",
    "Intimidating Prowess (Combat)",
    "Iron Will",
    
    "Leadership",
    "Lightning Reflexes",
    "Lightning Stance (Combat)",
    "Lunge (Combat)",
    
    "Magical Aptitude",
    "Manyshot (Combat)",
    "Martial Weapon Proficiency (Combat)",
    "Master Craftsman",
    "Maximize Spell (Metamagic)",
    "Medusa's Wrath (Combat)",
    "Mobility (Combat)",
    "Mounted Archery (Combat)",
    "Mounted Combat (Combat)",
    
    "Natural Spell",
    "Nimble Moves",
    
    "Penetrating Strike (Combat)",
    "Persuasive",
    "Pinpoint Targeting (Combat)",
    "Point-Blank Shot (Combat)",
    "Power Attack (Combat)",
    "Precise Shot (Combat)",
    
    "Quick Draw (Combat)",
    "Quicken Spell (Metamagic)",
    
    "Rapid Reload (Combat)",
    "Rapid Shot (Combat)",
    "Ride-By Attack (Combat)",
    "Run",
    
    "Scorpion Style (Combat)",
    "Scribe Scroll (Item Creation)",
    "Selective Channeling",
    "Self Sufficient",
    "Shatter Defenses (Combat)",
    "Shield Focus (Combat)",
    "Shield Master (Combat)",
    "Shield Proficiency (Combat)",
    "Shield Slam (Combat)",
    "Shot on the Run (Combat)",
    "Sickening Critical (Combat, Critical)",
    "Silent Spell (Metamagic)",
    "Simple Weapon Proficiency (Combat)",
    "Skill Focus",
    "Snatch Arrows (Combat)",
    "Spell Focus",
    "Spell Mastery",
    "Spell Penetration",
    "Spellbreaker (Combat)",
    "Spirited Charge (Combat)",
    "Spring Attack (Combat)",
    "Staggering Critical (Combat, Critical)",
    "Stand Skill (Combat)",
    "Stealthy",
    "Step Up (Combat)",
    "Still Spell (Metamagic)",
    "Strike Back (Combat)",
    "Stunning Critical (Combat, Critical)",
    "Stunning Fist (Combat)",
    
    "Throw Anything (Combat)",
    "Tiring Critical (Combat, Critical)",
    "Toughness",
    "Tower Shield Proficiency (Combat)",
    "Trample (Combat)",
    "Turn Undead",
    "Two-Weapon Defense (Combat)",
    "Two-Weapon Fighting (Combat)",
    "Two-Weapon Rend (Combat)",
    
    "Unseat (Combat)",
    
    "Vital Strike (Combat)",
    
    "Weapon Finesse (Combat)",
    "Weapon Focus (Combat)",
    "Weapon Specialization (Combat)",
    "Whirlwind Attack (Combat)",
    "Widen Spell (Metamagic)",
    "Wind Stance (Combat)"
};


#endif /* Feats_h */
